// 작성자: bumpsgoodman

#ifndef __ERROR_CODE_H
#define __ERROR_CODE_H

#define ERROR_CODE_SUCCESS  1
#define ERROR_CODE_FAIL     0

#define ERROR_CODE_SUCCEEDED(errorCode) ((errorCode) & ERROR_CODE_SUCCESS)
#define ERROR_CODE_FAILED(errorCode) ((errorCode) > 1)

#define ERROR_CODE_MAJOR    16

// ServerInfo
#define ERROR_CODE_CONFIG_MANAGER  (1 << ERROR_CODE_MAJOR)
#define ERROR_CODE_CONFIG_MANAGER_INVALID_CONFIG_FILE_EXTENSION     ERROR_CODE_CONFIG_MANAGER + 0
#define ERROR_CODE_CONFIG_MANAGER_FAILED_INIT_PARSER                ERROR_CODE_CONFIG_MANAGER + 1
#define ERROR_CODE_CONFIG_MANAGER_FAILED_PARSE_INI_FILE             ERROR_CODE_CONFIG_MANAGER + 2
#define ERROR_CODE_CONFIG_MANAGER_FAILED_PARSE_HTTP_PORT            ERROR_CODE_CONFIG_MANAGER + 3
#define ERROR_CODE_CONFIG_MANAGER_FAILED_PARSE_HTTPS_PORT           ERROR_CODE_CONFIG_MANAGER + 4
#define ERROR_CODE_CONFIG_MANAGER_FAILED_PARSE_CERT_PATH            ERROR_CODE_CONFIG_MANAGER + 5
#define ERROR_CODE_CONFIG_MANAGER_FAILED_PARSE_PRIVATE_KEY_PATH     ERROR_CODE_CONFIG_MANAGER + 6

// HttpRedirector
#define ERROR_CODE_REDIRECTOR   (2 << ERROR_CODE_MAJOR)
#define ERROR_CODE_REDIRECTOR_FAILED_CREATE_THREAD              ERROR_CODE_REDIRECTOR + 0
#define ERROR_CODE_REDIRECTOR_FAILED_CREATE_SOCKET              ERROR_CODE_REDIRECTOR + 1
#define ERROR_CODE_REDIRECTOR_FAILED_BIND_SOCKET                ERROR_CODE_REDIRECTOR + 2
#define ERROR_CODE_REDIRECTOR_FAILED_LISTEN_SOCKET              ERROR_CODE_REDIRECTOR + 3
#define ERROR_CODE_REDIRECTOR_FAILED_CREATE_EPOLL               ERROR_CODE_REDIRECTOR + 4
#define ERROR_CODE_REDIRECTOR_FAILED_WATCH_EPOLL_DESCRIPTER     ERROR_CODE_REDIRECTOR + 5
#define ERROR_CODE_REDIRECTOR_BUFFER_OVERFLOW                   ERROR_CODE_REDIRECTOR + 6
#define ERROR_CODE_REDIRECTOR_FAILED_INIT_ADDR_POOL             ERROR_CODE_REDIRECTOR + 7

// RequestHandler
#define ERROR_CODE_REQUEST_HANDLER   (3 << ERROR_CODE_MAJOR)
#define ERROR_CODE_REQUEST_HANDLER_FAILED_CREATE_THREAD              ERROR_CODE_REQUEST_HANDLER + 0
#define ERROR_CODE_REQUEST_HANDLER_FAILED_CREATE_SOCKET              ERROR_CODE_REQUEST_HANDLER + 1
#define ERROR_CODE_REQUEST_HANDLER_FAILED_BIND_SOCKET                ERROR_CODE_REQUEST_HANDLER + 2
#define ERROR_CODE_REQUEST_HANDLER_FAILED_LISTEN_SOCKET              ERROR_CODE_REQUEST_HANDLER + 3
#define ERROR_CODE_REQUEST_HANDLER_FAILED_CREATE_EPOLL               ERROR_CODE_REQUEST_HANDLER + 4
#define ERROR_CODE_REQUEST_HANDLER_FAILED_WATCH_EPOLL_DESCRIPTER     ERROR_CODE_REQUEST_HANDLER + 5
#define ERROR_CODE_REQUEST_HANDLER_BUFFER_OVERFLOW                   ERROR_CODE_REQUEST_HANDLER + 6
#define ERROR_CODE_REQUEST_HANDLER_FAILED_PARSE_METHOD               ERROR_CODE_REQUEST_HANDLER + 7
#define ERROR_CODE_REQUEST_HANDLER_NOT_SUPPORTED_METHOD              ERROR_CODE_REQUEST_HANDLER + 8

typedef unsigned int error_code_t;

void ErrorCode_SetLastError(const error_code_t errorCode);
error_code_t ErrorCode_GetLastError(void);

const char* ErrorCode_GetErrorDetail(const error_code_t errorCode);
const char* ErrorCode_GetLastErrorDetail(void);

#endif // __ERROR_CODE_H