// 작성자: bumpsgoodman

#ifndef __ERROR_CODE_H
#define __ERROR_CODE_H

#define ERROR_CODE_SUCCESS  1
#define ERROR_CODE_FAIL     0

#define ERROR_CODE_SUCCEEDED(errorCode) ((errorCode) & ERROR_CODE_SUCCESS)
#define ERROR_CODE_FAILED(errorCode) ((errorCode) > 1)

#define ERROR_CODE_MAJOR    (1 << 16)

// ServerInfo
#define ERROR_CODE_SERVER_INFO  ERROR_CODE_MAJOR + 0
#define ERROR_CODE_SERVER_INFO_INVALID_FILE_EXTENSION  ERROR_CODE_SERVER_INFO + 0
#define ERROR_CODE_SERVER_INFO_FAILED_INIT_INI_PARSER  ERROR_CODE_SERVER_INFO + 1
#define ERROR_CODE_SERVER_INFO_FAILED_PARSE_INI_FILE   ERROR_CODE_SERVER_INFO + 2
#define ERROR_CODE_SERVER_INFO_FAILED_GET_HTTP_PORT    ERROR_CODE_SERVER_INFO + 3
#define ERROR_CODE_SERVER_INFO_FAILED_GET_HTTPS_PORT   ERROR_CODE_SERVER_INFO + 4

// HttpRedirector
#define ERROR_CODE_REDIRECTOR   ERROR_CODE_MAJOR + 1
#define ERROR_CODE_REDIRECTOR_FAILED_CREATE_THREAD  ERROR_CODE_REDIRECTOR + 0
#define ERROR_CODE_REDIRECTOR_FAILED_CREATE_SOCKET  ERROR_CODE_REDIRECTOR + 1
#define ERROR_CODE_REDIRECTOR_FAILED_BIND_SOCKET    ERROR_CODE_REDIRECTOR + 2
#define ERROR_CODE_REDIRECTOR_FAILED_LISTEN_SOCKET  ERROR_CODE_REDIRECTOR + 3
#define ERROR_CODE_REDIRECTOR_FAILED_CREATE_EPOLL   ERROR_CODE_REDIRECTOR + 4

typedef unsigned int error_code_t;

void ErrorCode_SetLastError(const error_code_t errorCode);
error_code_t ErrorCode_GetLastError(void);

const char* ErrorCode_GetErrorDetail(const error_code_t errorCode);
const char* ErrorCode_GetLastErrorDetail(void);

#endif // __ERROR_CODE_H